1.3.0 add githubinit and githubpushinitial

diff --git a/common b/common
--- a/common
+++ b/common
@@ -1,19 +1,16 @@
-##
+#!/bin/bash
+#
 # Shared functionality between GitHub utilities
-##
 
-# Constants
-readonly CONFIG_FILE="github.cfg"
+set -e
 
 # Load config file
-source $CONFIG_FILE &&
+source github.cfg
 
 # Check args and initialize project info
 if [ $# -ne 2 ]; then
-    echo "Error: Missing args, expected <project_name> <description>"
+    echo "Error: Wrong args, expected <project_name> <description>"
     exit 1
 fi
 project_name=$1
 description=$2
-
-
